const Koa = require('koa')
const serveFiles = require('./serve-files')
const setupServer = require('./setup-server')
const setupSession = require('./setup-session')
const setupTwitter = require('./setup-twitter')
const setupPassport = require('./setup-passport')
const setupJiber = require('./setup-jiber')

const app = new Koa()
const server = setupServer(app)
const sessionStore = setupSession(app)
setupPassport(app)
setupTwitter(app)
setupJiber(app, server, sessionStore).catch(console.log)
serveFiles(app)
