module.exports = {
  // actions
  COMMENT: 'COMMENT',
  CREATE: 'CREATE',
  DELETE_COMMENT: 'DELETE_COMMENT',
  DELETE_POST: 'DELETE_POST',
  UPDATE: 'UPDATE',
  VOTE: 'VOTE',

  // sort
  TRENDING: 'TRENDING',
  TOP: 'TOP',
  NEW: 'NEW',

  // statuses
  PLANNED: 'PLANNED',
  IN_PROGRESS: 'IN_PROGRESS',
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  COMPLETE: 'COMPLETE'
}
